controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    # IMPORTANT: diff_drive_controller subscribes to TwistStamped
    use_stamped_vel: true

    left_wheel_names:  ["front_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]

    wheel_radius: 0.065

    # You MUST set this to your real wheel separation (center-left to center-right).
    # Use your dimensions.xacro wheel_y_offset:
    # wheel_separation = 2 * wheel_y_offset
    wheel_separation: 0.434
    base_frame_id: base_footprint
    odom_frame_id: odom
    enable_odom_tf: true
